# travis needs sudo permission
sudo: required

services:
  - docker

before_install:
  - docker build -t dennisxiao/docker-react -f Dockerfile.dev .

script:
  - docker container run dennisxiao/docker-react npm run test -- --coverage